### ISSUE TITLE
API Call to Station Controller

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/TransportScheduler#10]
API call to station controller fetches station schedule.

In order to complete this user story, an appropriate RESTful library must be integrated with station controller. A good way to check this would be to issue the API call from curl of the form http://localhost/schedule/stn_code and check all the output. We must receive all the schedule entries of a station in tuple form.

**Comment by prasadtalasila** [comment]
For this to be complete, simple user query controller (UQC) must be in place as an Elixir system process. UQC process communicates with the station controller process.

**Comment by ahaldar** [comment]
Maru framework to be used. Placeholder code ready in api.ex, needs to be modified to retrieve schedule from Station through NC by mapping stn_code to pid.

**Comment by suhasspai** [comment]
Sir,
I have uploaded the proposed API design file at the root of the repo, from my side, after reading through the resources you provided.

**Comment by prasadtalasila** [comment]
For now, the station (network) controller and UC/UQC communicate using genserver.
