### ISSUE TITLE
UC and UQC API Implementation

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/TransportScheduler#11]
Implementation using Maru or any other RESTful API library

**Comment by ahaldar** [comment]
The placeholder API that I had created uses Maru API library, found on the list at https://github.com/h4cc/awesome-elixir
@suhasspai I remember Swagger being mentioned, so see if this is useful: https://github.com/falood/maru_swagger

**Comment by suhasspai** [comment]
A clean RESTful API with Maru successfully implemented. Initialisation is done in {base_url}/api/ and then the other queries can be carried out on /api/station/schedule, /api/search etc.

**Comment by suhasspai** [comment]
I am unable to supply a GET request by not passing parameters in the URL. Something like:
`curl -X GET --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{"source": 5, "date": "11-09-2016"}' 'http://127.0.0.1:8880/api/station/schedule'`
generates a response as
`Server Error`
each time. The GET request is fulfilled if I issue this command:
`curl -X GET 'http://127.0.0.1:8880/api/station/schedule?source=5&date=11-09-2016'`
The response is:
`Alnavar Junction`

To be able to pass parameters within my cURL request and not in my URL, I must issue a POST request like this:
`curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{"source": 5, "date": "11-09-2016"}' 'http://127.0.0.1:8880/api/station/schedule'`
which gives a response like:
`Alnavar Junction`

For this reason, I am implementing all of them as POST requests that generate responses in response to the embedded parameters in the cURL command.
