### ISSUE TITLE
Query Completion at Network Constructor

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/TransportScheduler#12]
Tests are:
1. Query from one station to another station.
2. Query from network constructor to a station.
3. Answer from a station to network constructor.
4. Query from network constructor to a station and answer coming back from another station.

**Comment by suhasspai** [comment]
Sir, for some reason, I am unable to test any functionality since a Station is unable to be created. I have locally implemented the message passing mechanism but cannot test the same until this bug is resolved.

**Comment by suhasspai** [comment]
Tests have been added. GenStateMachine itself is used, since usage of GenStateMachine and GenServer causes function clashes that can't be handled cleanly.

**Comment by suhasspai** [comment]
Message passing from station to NC added; needs to be implemented in actual network code.

**Comment by ahaldar** [comment]
Itinerary is updated and passed as expected: NC -> Src Station -> Next Station -> Dst Station -> NC.
Yet to integrate with API end.
