### ISSUE TITLE
UQC API meaningful results

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/TransportScheduler#14]

**Comment by suhasspai** [comment]
All functionality of the API gives meaningful results. Slight changes in API include:
1. Get schedule of a station: GET request to /api/station/schedule.
2. Add entry to a station's schedule: POST request to /api/station/schedule/add.
3. Update entry in a station's schedule: PUT request to /api/station/schedule/update.
4. Get state of a station: GET request to /api/station/state.
5. Update state of a station: PUT request to /api/station/state/update.

POST and PUT requests can be provided data in JSON format, GET request has data embedded in URL (unfortunately). An alternate was to not include it in the URL in the request is like this:
```
curl -X GET -G http://localhost:8880/api/station/schedule -d "station_code=5&date=11-09-2016"
```
But the data eventually gets appended to the URL.
