### ISSUE TITLE
data polymorphism in elixir

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/TransportScheduler#15]

**Comment by ahaldar** [comment]
Protocols are the built-in way to achieve polymorphism:
http://elixir-lang.org/getting-started/protocols.html

I have tested this independent of our TransportScheduler application. Our StationStruct is still changing based on requirement. I can put protocols in place easily as soon as the structures are settled.

**Comment by ahaldar** [comment]
Simple pattern matching in function argument list with various struct types for overloading functions is a neater solution.
