### ISSUE TITLE
Group itineraries at NC

### ISSUE THREAD

**Issue by ahaldar** [prasadtalasila/TransportScheduler#17]
When NC receives multiple potential itinerary results from destination, these must be collected and best option based on the given constraints must be chosen. In the future, batch queries are to be submitted to the application. The NC will then receive results from multiple destinations, and will need a separate collection of itineraries for each such query. Within each collection, NC will have selection and timeout mechanism separately.

**Comment by suhasspai** [comment]
Itineraries are added to a list one by one, and the fastest itinerary can found by walking through this list of possible itineraries.
