### ISSUE TITLE
Support for concurrent itineraries at UQC

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/TransportScheduler#20]
Concurrent requests need to be supported at UQC; each request gets its own timeout value of 0.5sec.

Choose proper data structure for storing query results. We want to send N (=10) itinerary results to the user.

**Comment by prasadtalasila** [comment]
There should be a mapping between incoming user query request socket, query-iternerary map and timeout.

A good coding idiom / library needs to be found for concurrent user query request socket handling.

**Comment by ahaldar** [comment]
For timeout per query, Process.send_after(dest, msg, time, opts \\ []) to self() should do the trick. On receiving this, process stops further search.
Similar to http://stackoverflow.com/questions/32085258/how-to-run-some-code-every-few-hours-in-phoenix-framework.

**Comment by suhasspai** [comment]
http://holyxiaoxin.github.io/async-tasks-benchmark/
This link contains pretty much what we need: the person who wrote this blog did benchmarks for asynchronous (concurrently executing) tasks and plotted the requisite graphs as well. I'll mostly make use of HTTPoison itself for the testing.

**Comment by prasadtalasila** [comment]
For the conference paper, we were collecting query statistics from NC / UQC. Using the async task, we can collect the same from the user point of view.
If this work is complete, the corresponding test can be put in travis pipeline so that the performance results become visible for all the commits. We can then make sure that the code never becomes slow, at least not unintentionally.
