### ISSUE TITLE
code quality toolset

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/TransportScheduler#22]
a linter and static code analysis tool for Elixir language. A web-based service that we can integrate with the github commits would be good as well.

**Comment by ahaldar** [comment]
Credo https://github.com/rrrene/credo.

**Comment by ahaldar** [comment]
Capable of being integrated with Travis using Pronto https://github.com/carakan/pronto-credo.
Gives pull request comments as described here https://blog.fazibear.me/automated-elixir-code-review-with-github-credo-and-travis-ci-986cd56b8f02#.t3r4fern0.

**Comment by prasadtalasila** [comment]
credo integrated into codeclimate.yml file in commit c54d745. 

do we still need pronto-credo? pronto-credo doesn't seem very useful in travis-ci workflow. If we don't need pronto-credo, please close this issue.

**Comment by ahaldar** [comment]
Pronto-credo seems unnecessary. Credo is displaying nicely in Travis.
