### ISSUE TITLE
search query response collection in a separate process

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/TransportScheduler#24]
The itinerary search queries are all being collected in NC at the moment, making NC a bottleneck. We can change the scenario to the following.

1. A query goes to NC
1. NC spawns a query response collector process
1. Adds the process id of the query response collector to the query structure.
1. Gives the query to source station
1. Destination passes the response to query response collector process
1. Query response collector gives the set of responses to UQC

**Comment by suhasspai** [comment]
This [commit](https://github.com/prasadtalasila/TransportScheduler/commit/2665f06b823fca53a95af0c7c6366488a6bf7f34) fixes the issue. Added new file qc.ex that contains module named QC that collects itineraries for each query.
