### ISSUE TITLE
performance testing in travis

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/TransportScheduler#28]
[Joseph Kain](https://github.com/joekain) wrote [elixir-life](https://github.com/joekain/elixir-life) project which has the exprof as a mix task. Please see [Profile.ex](https://github.com/joekain/elixir-life/blob/master/lib/profile.ex) for more details. He uses [eflame](https://github.com/proger/eflame) to draw the performance graphs which will help in looking at the bottlenecks. For a way to include eflame as dependency, see his [mix.exs](https://github.com/joekain/elixir-life/blob/master/mix.exs) file. An explanation of his code is available [profile](http://learningelixir.joekain.com/profiling-elixir/), [profile-2](http://learningelixir.joekain.com/profiling-elixir-2/).

As shown in the comments of profile-elixir-2 article, see RickHull's [mix task](https://github.com/rickhull/conway_deathmatch/blob/elixir/perf/mix.ex) for profiling.

Joseph Kain's [bmark](https://github.com/joekain/bmark) tool seems useful as well. An explanation of bmark tool is [available](http://learningelixir.joekain.com/comparing-benchmark-results-with-elixir/).

[benchee](https://github.com/PragTob/benchee) and [benchfella](https://github.com/alco/benchfella) helps benchmark unit tests. This is especially useful for integration kind of unit tests. We were hoping to get performance results at the level of functions of TransportScheduler. Both these tools help us get such performance numbers. Of the two tools, benchee seems more promising.

Ref: http://learningelixir.joekain.com/optimizing-elixir-posts/

**Comment by ahaldar** [comment]
Added ExProf as Mix Task, command added to Travis.

**Comment by prasadtalasila** [comment]
Necessary documentation put in place on [code profiling](https://github.com/prasadtalasila/TransportScheduler/wiki/Code-Profiling) wiki page.
