### ISSUE TITLE
selection on mailbox messages

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/TransportScheduler#31]
Erlang provides pattern matching on mailbox messages [1](http://erlang.org/doc/getting_started/conc_prog.html), [2](https://www.safaribooksonline.com/library/view/erlang-programming/9780596803940/ch04s03.html). Even Elixir has the message receive pattern [matching](http://elixir-lang.org/getting-started/processes.html#send-and-receive) capability. 

Also see an explanation on this [stackoverflow](https://cs.stackexchange.com/questions/19506/differences-between-the-actor-model-and-communicating-sequential-processes-csp) answer.

We can probably use them to flush out the stale queries faster and to give priority to active queries at a station process.

**Comment by prasadtalasila** [comment]
@bgargi @SuhasHebbar can you answer this question based on what you know now?

**Comment by prasadtalasila** [comment]
If there is a pluggable system for mailbox (incoming message processing) of an erlang process, we can put in our own functions to pick the next message from the mailbox.

**Comment by prasadtalasila** [comment]
@SuhasHebbar 
Please check [selective receives](http://learnyousomeerlang.com/more-on-multiprocessing#selective-receives) and example. The coding idiom seems to satisfy our requirement of first selecting all the pending messages belonging to one query and then selecting one message with least cost.

**Comment by SuhasHebbar** [comment]
I think the Selective receives will not help us to know if a query is stale or not before we start processing it as we need to query the Registry to know the query's status. (Selective receives only work with pattern matching)

**Comment by prasadtalasila** [comment]
@SuhasHebbar 
This we can talk about when we implement a queue management for a station. For now, our prevailing idea is that GenServer is not the right place to do it. We may need an input processor which filters, aggregates and then hands over the queries to the station process.

@bgargi is going to summarize our lessons about selective reception on GenServer page. We will pursue selective reception later.
