### ISSUE TITLE
Activeness of query in network into ETS

### ISSUE THREAD

**Issue by suhasspai** [prasadtalasila/TransportScheduler#34]
The `NetworkConstructor` module keeps track of the active queries (the queries whose results are awaited by the user and the itineraries are currently being searched in the network) in the form a `Map` data structure, and there is an abstracted client function `check_active/2` that returns the status of a given query (`true` for active, `false` for inactive). This needs to be implemented in the ETS table at the UQC.

**Comment by prasadtalasila** [comment]
The active status is to be maintained by query collector of each query. Each respective query collector writes / updates the status of an active query. Any node interested in knowing the status of a query looks up (reads) from ETS table. Entries in the table must time out to remove stale entries. A timedout entry would be removed from ETS table. This time out can be set to 5 minutes for now. A station can look up for active status of a query in ETS and find three possible responses.

* active --> station proceeds with processing the query
* stale --> station discards the query
* no entry --> station discards the query

**Comment by prasadtalasila** [comment]
The problem has been solved using query collector module.
