### ISSUE TITLE
separation of UC and UQC from API module

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/TransportScheduler#40]

**Comment by VedangW** [comment]
@suhasspai can you please help by explaining why UC is not present in api.ex anywhere?

**Comment by prasadtalasila** [comment]
The code in api.ex combines the UQC and UC elements of [API](https://github.com/prasadtalasila/TransportScheduler/wiki/API-Design) end points. It is better to separate them using two processes that use Maru module to serve the different API end points. The separation should be as per the [API design](https://github.com/prasadtalasila/TransportScheduler/wiki/API-Design) page.

**Comment by VedangW** [comment]
@prasadtalasila Sir, while compiling after making the changes, I get this warning that I am not able to comprehend because I can't find the file gen_server.ex in the folder lib. What can this be about?
warning: this clause cannot match because a previous clause at line 11 always matches
  lib/gen_server.ex:1

**Comment by prasadtalasila** [comment]
@VedangW It looks like a module import error. The gen_server is a built in module of elixir. Are you sure that you have the following statement in your new elixir file?

```elixir
use GenServer, async: true
```

**Comment by VedangW** [comment]
@prasadtalasila Yes sir, it's already there. I am looking at alternate solutions now.

**Comment by prasadtalasila** [comment]
1. Update all the tests for refactoring.
1. Add one test for each API call in UC and UQC.

**Comment by VedangW** [comment]
@prasadtalasila Sir, how do I ensure that the initialization happens in both maru modules, UQC and UC? Do I need to start a UQC process in UC for that?
For eg.,
UQC has this:
https://pastebin.com/DgVy9RwQ
What would happen if someone puts a query which routes through UC?

**Comment by prasadtalasila** [comment]
It makes sense to put the initialization code in UC. The search part of API anyway goes into UQC. The [itinerary search code](https://github.com/prasadtalasila/TransportScheduler/blob/dev/lib/ts/api.ex#L50-L88) can be put in [try-catch-rescue](https://elixir-lang.org/getting-started/try-catch-and-rescue.html) for the scenario of uninitialized network.

**Comment by VedangW** [comment]
@prasadtalasila Sir what you suggested about the try-catch-rescue clause is done.
I have so far separated UC and UQC as two separate modules, with the ETS tables in UQC and the initialisation in UC. All files are compiling without errors or warnings. However, `mix test` and `_build/dev/rel/ts/bin/ts console` don't work and result in crash dumps. Here are the errors I get from:
`mix test`:
`
** (Mix) Could not start application maru: Maru.start(:normal, []) returned an error: an exception was raised:
    ** (UndefinedFunctionError) function API.init/1 is undefined (module API is not available)
        API.init([])
        (plug) lib/plug/adapters/cowboy.ex:191: Plug.Adapters.Cowboy.dispatch_for/2
        (plug) lib/plug/adapters/cowboy.ex:48: Plug.Adapters.Cowboy.args/4
        (plug) lib/plug/adapters/cowboy.ex:137: Plug.Adapters.Cowboy.child_spec/4
        (maru) lib/maru/supervisor.ex:14: anonymous fn/4 in Maru.Supervisor.init/1
        (elixir) lib/enum.ex:1623: Enum."-reduce/3-lists^foldl/2-0-"/3
        (maru) lib/maru/supervisor.ex:12: anonymous fn/2 in Maru.Supervisor.init/1
        (elixir) lib/enum.ex:1623: Enum."-reduce/3-lists^foldl/2-0-"/3
`
and `_build/dev/rel/ts/bin/ts console`:
`
{"init terminating in do_boot",{load_failed,['Elixir.API']}}

Crash dump is being written to: erl_crash.dump...done
init terminating in do_boot ()
`
After digging a bit online, I found this page which helps a bit but I can't relate it to how to solve this particular problem:
http://erlang.org/documentation/doc-5.1/erts-5.1/doc/html/crash_dump.html
What could the problem be?

**Comment by prasadtalasila** [comment]
There are references to API module in your code. The dump messages clearly indicate so. Please replace API invocations with UC/UQC invocations as appropriate.

**Comment by VedangW** [comment]
@prasadtalasila Sir, sorry for the late follow up, I was not well yesterday.

I didn't find any references to API in my code, I replaced as many as I could find, which is why the project compiles in the first place. The error doesn't point out where the invocation, `API.init\1` might be, which I thought you could help me find. There are no references to API in lib/ts or in lib/mix (expect in the namespace `:api`) . I also looked through most of the other directories including config, rel, script, etc. but couldn't find API anywhere except in the url, i,e. `http://localhost:8880/api...` or in the comments. 

Could it be possible that having a namespace `:api` in Maru means that there should be an API file?

**Comment by prasadtalasila** [comment]
@VedangW Please make a commit of the code that is giving the error and provide a reference for the same in this issue.

**Comment by prasadtalasila** [comment]
The problem will be fixed in TS-v1.0-alpha branch with fresh code. Fixing the master branch is not a priority right now.
