### ISSUE TITLE
update dependencies to latest stable releases.

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/TransportScheduler#49]
Suggested ones are:    
Gen State Machine v2.0.0, Erlang OTP 20.0, Elixir v1.5

The problem is that the station.ex uses both synchronous and asynchronous functions of gen state machine. We need to convert all the synchronous functions to asynchronous before we attempt an upward revision of all the packages.

This issue would also solve #9.

**Comment by prasadtalasila** [comment]
@SuhasHebbar 
A suggestion: The state machine code layout in [FSM](https://github.com/sasa1977/fsm) module is a lot cleaner than in the Gen State Machine. FSM also fits into gen_server. We can go with that for the station process.

**Comment by SuhasHebbar** [comment]
In a blog post José Valim advices against using mocks in elixir and instead suggests using something similiar to dependency injection for testing.
Would you have any problem with the refactored Station module and its tests be structured keeping the blog post in mind.
http://blog.plataformatec.com.br/2015/10/mocks-and-explicit-contracts/

**Comment by prasadtalasila** [comment]
The article is fantastic. By all means it provides good advice. Where there is a choice, I would prefer **Mocks as Locals** kind of dependency over **dependency injection** via configuration.

In Java world, dependency injection via configuration is strictly frowned upon for unit tests. For integration tests thought, it is a good advice.

In the article, [mox](https://github.com/plataformatec/mox) has been suggested. By all means use the module.

@SuhasHebbar Thanks for bringing up the article.

**Comment by prasadtalasila** [comment]
suggestions incorporated into ts-v1.0-alpha branch.
