### ISSUE TITLE
wiki page on Erlang concurrency model

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/TransportScheduler#5]
A short summary of Erlang concurrency model as used by Elixir. Also see the Actor concurrency model chapter in Seven Concurrency Models in Seven Weeks book.

**Comment by suhasspai** [comment]
I have updated the information we discussed in today's meeting. Will read up the chapter and complete the wiki.

**Comment by suhasspai** [comment]
I have updated the Wiki after obtaining some information from the chapter on Actor Model in "Seven Concurrency Models in Seven Weeks".
