### ISSUE TITLE
wiki page for proposed architecture

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/TransportScheduler#57]
New wiki page needs to be created for architecture so that all of us are on the same page.

**Comment by prasadtalasila** [comment]
The [wiki page](https://github.com/prasadtalasila/TransportScheduler/wiki/TS-v1.0-Proposed-Architecture) updated.

**Comment by prasadtalasila** [comment]
@SuhasHebbar The following updates are required for the [wiki page](https://github.com/prasadtalasila/TransportScheduler/wiki/TS-v1.0-Proposed-Architecture).

1. The technical term **thread** is used on the wiki page. An example sentence: "Each station is to be allocated a dedicated thread on BeamVM." We don't use the term threads in the project. Hence you are requested to reword the term to something that is compatible in Elixir language.
1. The sequence diagram does not have the corresponding PlantUML. Please embed the PlantUML code into the wiki page. For a good way to achieve code embedding, please see [example page](https://github.com/AutolabJS/autolabcli/wiki/Call-graphs-(Sequence-diagrams)).

**Comment by prasadtalasila** [comment]
@SuhasHebbar is the wiki page updated?

**Comment by SuhasHebbar** [comment]
The discussed work has been done except for the PlantUML code for the sequence diagram.
It will be put up soon.

**Comment by prasadtalasila** [comment]
@SuhasHebbar 

I changed the structure of the wiki page a bit. The following further improvements are possible:

1. In [station state](https://github.com/prasadtalasila/TransportScheduler/wiki/TS-v1.0-Proposed-Architecture#station-state), you can give the data structures used for storing the state. You can also justify the selection of the data structures with algorithmic complexity of using them for our typical usage scenarios.
1. Better explanation with good diagram is needed under [dependency injection](https://github.com/prasadtalasila/TransportScheduler/wiki/TS-v1.0-Proposed-Architecture#dependency-injection).
1. Explanation of sequence and state machine diagrams in the language of the application.
1. You can copy the list of station tests from issue #53. You can also specify the suggested testing idioms here.
1. You can also justify the structure of the query format and update the same for other means table.
1. In [Registry and Network Constructor](https://github.com/prasadtalasila/TransportScheduler/wiki/TS-v1.0-Proposed-Architecture#registry-and-network-constructor), separate registry from network constructor.
1. Explain about one behavior for registry and its possible implementation using [rePG2](https://github.com/ericentin/repg2).

**Comment by prasadtalasila** [comment]
@SuhasHebbar Please complete list of pending corrections as identified in the previous comment of this issue.

**Comment by prasadtalasila** [comment]
The [proposed architecture](https://github.com/prasadtalasila/TransportScheduler/wiki/TS-v1.0-Proposed-Architecture) page has been updated.
