### ISSUE TITLE
Elixir RESTful API implementation

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/TransportScheduler#6]
Look for a scalable RESTful API library for elixir and use it to in the Station Controller. Appropriate reference links to be updated on [References](https://github.com/prasadtalasila/TransportScheduler/wiki/References) page.

**Comment by ahaldar** [comment]
I have investigated some potential libraries, and the References wiki page has the relevant links.
I still need to spend some time to understand what would fit best.
