### ISSUE TITLE
Update polymorphism docs

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/TransportScheduler#65]
Please update [Behavior and Polymorphism](https://github.com/prasadtalasila/TransportScheduler/wiki/Behaviour,-Protocols-and-Polymorphism) page.

**Comment by prasadtalasila** [comment]
Only pending work here: Interaction of behaviors-protocols-modules-structs.

**Comment by prasadtalasila** [comment]
@suryapratapmehra There are two chapters in "Programming Elixir, Dave Thomas" book that are relevant to our work.

* Ch 21. Linking Modules: Behaviours and Use
* Ch 22. Protocols - Polymorphic Functions

**Comment by prasadtalasila** [comment]
@suryapratapmehra did you take a look at chapters 21 and 22 of "Programming Elixir" book? If not, please do that and update the wiki pages based on new insights from these two chapters.

**Comment by suryapratapmehra** [comment]
Yes. The pages have been updated to include the new insights from these two chapters.

**Comment by prasadtalasila** [comment]
The pages moved to [Behaviours, Protocols, Modules and Structs](https://github.com/prasadtalasila/TransportScheduler/wiki/Behaviours,-Protocols,-Modules-and-Structs).
