### ISSUE TITLE
Update test patterns wiki page with idiomatic unit tests

### ISSUE THREAD

**Issue by SuhasHebbar** [prasadtalasila/TransportScheduler#75]
in Station unit tests non determinism has to be removed when asserting on expectations in the parallel process. This can be done by busy waiting on the condition that the Station process is no longer alive.

**Comment by SuhasHebbar** [comment]
The methodology discussed in this issue needs to be documented under testing in the wiki.

**Comment by SuhasHebbar** [comment]
The proposed idiom works as expected.

It has been incorporated into the station_tests in the following form.
```elixir
#Send query to station
		Station.send_query(pid, itinerary)
		#Stop station normally
		Station.stop(pid)

		#Wait for the Station process to terminate
		wait_for_process_termination(pid)

		assert_receive :query_forwarded
```

**Comment by SuhasHebbar** [comment]
wait_for_process_termination/1 can be implemented as given below
```elixir
	def wait_for_process_termination(pid) do
		if Process.alive?(pid) do
			:timer.sleep(10)
			wait_for_process_termination(pid)
		end
	end
```

**Comment by prasadtalasila** [comment]
sounds good. Let's go ahead with this coding idiom.

@suryapratapmehra please understand this coding idiom and explain it under Tests section of the coding style.

**Comment by prasadtalasila** [comment]
The [test patterns](https://github.com/prasadtalasila/TransportScheduler/wiki/Testing-Patterns) webpage has been updated.
