### ISSUE TITLE
Overhead of sending an itinerary

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/TransportScheduler#84]
We shall use new query and itinerary structures to find the messaging over between Elixir processes.

**Comment by prasadtalasila** [comment]
The demonstrative coding snippets to be committed to **benchmarks** branch.

**Comment by SuhasHebbar** [comment]
I have sent a PR for benchmarking the message passing of the itinerary between processes.
The benchmarks in #91  measure the number of messages processed by a GenServer within 30s without performing any computation on the received message.
The cases include in the benchmarks are for itineraries of length ranging from 0 to 64 and for 1 - 10,000 concurrent message senders.

**Comment by prasadtalasila** [comment]
merged.
